version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: hep-companion-app
    ports:
      - "3000:3000"
    volumes:
      # Mount source code for hot-reload
      - .:/app
      # Prevent node_modules from being overwritten by mount
      - /app/node_modules
      # Prevent .next from being overwritten by mount
      - /app/.next
    env_file:
      - .env.local
    environment:
      # Override any environment variables as needed
      NODE_ENV: development
      WATCHPACK_POLLING: true # For hot-reload on some systems
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - hep-network

networks:
  hep-network:
    driver: bridge 