apiVersion: v1
kind: Secret
metadata:
  name: hep-companion-secrets
type: Opaque
stringData:
  supabase-url: "YOUR_SUPABASE_URL"
  supabase-anon-key: "YOUR_SUPABASE_ANON_KEY"
  supabase-service-role-key: "YOUR_SUPABASE_SERVICE_ROLE_KEY"
  # Add other sensitive configuration here 