name: Docker Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build test image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: test
          load: true
          tags: hep-companion:test
          build-args: |
            NODE_VERSION=${{ matrix.node-version }}

      - name: Run unit tests
        run: |
          docker run --rm \
            -v $(pwd)/coverage:/app/coverage \
            hep-companion:test \
            npm run test:unit

      - name: Run integration tests
        run: |
          docker run --rm \
            -v $(pwd)/test-results:/app/test-results \
            -v $(pwd)/playwright-report:/app/playwright-report \
            hep-companion:test \
            npm run test:integration

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            coverage/
            test-results/
            playwright-report/

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        if: always()
        with:
          directory: ./coverage/
          fail_ci_if_error: false 